/*
 * GPIO_config.h
 *
 *  Created on: Feb 27, 2019
 *      Author: AyetAllah
 */

#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

#define NUMBER_PINS_IN_PORT 16
/***********************************Initialization Direction and Types******************************************/

#define GPIO_PORTA_PIN0_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN1_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN2_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN3_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN4_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN5_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN6_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN7_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN8_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN9_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN10_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN11_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN12_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN13_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN14_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTA_PIN15_DIR           OUTPUT_2MHZ_GP_PUSHPULL



#define GPIO_PORTB_PIN0_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN1_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN2_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN3_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN4_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN5_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN6_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN7_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN8_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN9_DIR            OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN10_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN11_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN12_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN13_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN14_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTB_PIN15_DIR           OUTPUT_2MHZ_GP_PUSHPULL

#define GPIO_PORTC_PIN13_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTC_PIN14_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTC_PIN15_DIR           OUTPUT_2MHZ_GP_PUSHPULL

#define GPIO_PORTD_PIN0_DIR           OUTPUT_2MHZ_GP_PUSHPULL
#define GPIO_PORTD_PIN1_DIR           OUTPUT_2MHZ_GP_PUSHPULL


/****************************Initialization Values***************************************/


#define GPIO_PORTA_PIN0_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN1_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN2_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN3_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN4_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN5_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN6_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN7_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN8_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN9_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTA_PIN10_VALUE     GPIO_PIN_HIGH
#define GPIO_PORTA_PIN11_VALUE     GPIO_PIN_HIGH
#define GPIO_PORTA_PIN12_VALUE     GPIO_PIN_HIGH
#define GPIO_PORTA_PIN13_VALUE     GPIO_PIN_HIGH
#define GPIO_PORTA_PIN14_VALUE     GPIO_PIN_HIGH
#define GPIO_PORTA_PIN15_VALUE     GPIO_PIN_HIGH



#define GPIO_PORTB_PIN0_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN1_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN2_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN3_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN4_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN5_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN6_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN7_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN8_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN9_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTB_PIN10_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTB_PIN11_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTB_PIN12_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTB_PIN13_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTB_PIN14_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTB_PIN15_VALUE      GPIO_PIN_HIGH

#define GPIO_PORTC_PIN13_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTC_PIN14_VALUE      GPIO_PIN_HIGH
#define GPIO_PORTC_PIN15_VALUE      GPIO_PIN_HIGH

#define GPIO_PORTD_PIN0_VALUE       GPIO_PIN_HIGH
#define GPIO_PORTD_PIN1_VALUE       GPIO_PIN_HIGH


#endif /* GPIO_CONFIG_H_ */
